microService:
  name: main
  repositoryName: multi-main
  containerPort: 3000
  mountEnvFile: false
  env:
    normal:
      API_GATEWAY_SERVER_HOST: "0.0.0.0"
      API_GATEWAY_SERVER_PORT: "3000"
      API_GATEWAY_CORS_ORIGIN: "http://localhost:8100,http://127.0.0.1:8100,http://localhost,capacitor://localhost"
      FEATURES_SERVICE_HOST: "0.0.0.0"
      FEATURES_SERVICE_PORT: "3003"
      AUTH_SERVICE_HOST: "0.0.0.0"
      AUTH_SERVICE_PORT: "3004"
      MAP_SERVICE_HOST: "multi-backend-map-service"
      MAP_SERVICE_PORT: "3005"
      RSS_SERVICE_HOST: "0.0.0.0"
      RSS_SERVICE_PORT: "3006"
      CARDS_SERVICE_HOST: "0.0.0.0"
      CARDS_SERVICE_PORT: "3007"
      SCHEDULE_SERVICE_HOST: "0.0.0.0"
      SCHEDULE_SERVICE_PORT: "3008"
      CONTACTS_SERVICE_HOST: "0.0.0.0"
      CONTACTS_SERVICE_PORT: "3009"
      NOTIFICATIONS_SERVICE_HOST: "0.0.0.0"
      NOTIFICATIONS_SERVICE_PORT: "3010"
      IMPORTANT_NEWS_SERVICE_HOST: "0.0.0.0"
      IMPORTANT_NEWS_SERVICE_PORT: "3011"
      CLOCKING_SERVICE_HOST: "0.0.0.0"
      CLOCKING_SERVICE_PORT: "3012"
      SOCIAL_NETWORK_SERVICE_HOST: "0.0.0.0"
      SOCIAL_NETWORK_SERVICE_PORT: "3013"
      CHATBOT_SERVICE_HOST: "0.0.0.0"
      CHATBOT_SERVICE_PORT: "3014"
      STATIC_PAGES_SERVICE_HOST: "0.0.0.0"
      STATIC_PAGES_SERVICE_PORT: "3015"
      CONTACT_US_SERVICE_HOST: "0.0.0.0"
      CONTACT_US_SERVICE_PORT: "3016"
      RESTAURANTS_SERVICE_HOST: "0.0.0.0"
      RESTAURANTS_SERVICE_PORT: "3017"
    secret:
      AUTH_SERVICE_JWT_SECRET: "changeit"