apiVersion: v1
kind: Secret
metadata:
  name: multi-backend-secrets-{{ .Values.microService.name }}
type: Opaque
data:
  {{- if and .Values.microService.env .Values.microService.env.secret }}
  {{- range $key, $val := .Values.microService.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}