variables:
  CURRENT_DIR: "dev/user-backend-nest/microservices/static-pages/"
  CURRENT_PROJECT: "static-pages"
  IMAGE_NAME: "backend/multi-static-pages"

include: "${CI_PROJET_DIR}/dev/user-backend-nest/template-ci.yml"
