apiVersion: v1
kind: Secret
metadata:
  name: multi-backend-secrets-main
type: Opaque
data:
  {{- if and .Values.image.service.env .Values.image.service.env.secret }}
  {{- range $key, $val := .Values.image.service.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}