apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}-{{ .Values.appService.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryUrl }}/{{ .Values.appService.repositoryName }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ $data := dict "Values" .Values }}
          livenessProbe:
            {{- include "helpers.get-common-health-probe" $data | nindent 12 }}
          readinessProbe:
            {{- include "helpers.get-common-health-probe" $data | nindent 12 }}
          env:
            {{ $data := dict "Values" .Values "env" .Values.appService.env }}
            {{- include "helpers.list-env-variables" $data | indent 12 }}
          command:
            {{  range .Values.image.nodeBaseCommand }}
            - {{ . | quote }}
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.appService.containerPort }}