apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace mongodb-secrets) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $mongodbRootPassword := (get $secretData "mongodb-root-password") | default (randAlphaNum 32 | b64enc) }}
  mongodb-root-password: {{ $mongodbRootPassword | quote }}