apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-multi-backend-{{ .Values.image.service.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}