common:
  config:
    DIRECTUS_API_URL: &directusApiUrl "changeit"
    DIRECTUS_API_BEARER_TOKEN: &directusApiBearerToken "changeit"

multi-microservice-auth:
  waitForDB: true
  appService:
    name: auth
    repositoryName: multi-auth
    path: /auth
    containerPort: 3004
    env:
      normal:
        AUTH_SERVICE_HOST: "0.0.0.0"
        AUTH_SERVICE_PORT: "3004"
        AUTH_SERVICE_CAS_URL_REQUEST_TGT: "changeit"
        AUTH_SERVICE_CAS_URL_REQUEST_ST: "changeit"
        AUTH_SERVICE_CAS_URL_VALIDATE_ST: "changeit"
        AUTH_SERVICE_CAS_URL_LOGOUT: "changeit"
        AUTH_SERVICE_UL_API_URL_USER_PROFILE: "changeit"
        AUTH_SERVICE_USERNAMES_CLEANUP_SCHEDULE: "0 0 * * * *"
        AUTH_SERVICE_USERNAMES_CLEANUP_NOT_USED_SINCE_IN_DAYS: "1"
        AUTH_SERVICE_CREDENTIALS_CLEANUP_SCHEDULE: "0 0 * * * *"
        AUTH_SERVICE_CREDENTIALS_CLEANUP_NOT_USED_SINCE_IN_DAYS: "30"
      secret:
        AUTH_SERVICE_UL_API_BEARER_TOKEN: "changeit"
        AUTH_SERVICE_JWT_SECRET: "changeit"

multi-microservice-cards:
  appService:
    name: cards
    repositoryName: multi-cards
    path: /cards
    containerPort: 3007
    env:
      normal:
        CARDS_SERVICE_HOST: "0.0.0.0"
        CARDS_SERVICE_PORT: "3007"
        CARDS_SERVICE_UL_API_URL_USER_CARDS: "changeit"
      secret:
        CARDS_SERVICE_UL_API_BEARER_TOKEN: "changeit"

multi-microservice-chatbot:
  appService:
    name: chatbot
    repositoryName: multi-chatbot
    path: /chatbot
    containerPort: 3014
    env:
      normal:
        CHATBOT_SERVICE_HOST: "0.0.0.0"
        CHATBOT_SERVICE_PORT: "3014"
        CHATBOT_SERVICE_UL_API_TOCK_URL: "changeit"

multi-microservice-clocking:
  appService:
    name: clocking
    repositoryName: multi-clocking
    path: /clocking
    containerPort: 3012
    env:
      normal:
        CLOCKING_SERVICE_HOST: "0.0.0.0"
        CLOCKING_SERVICE_PORT: "3012"
        CLOCKING_SERVICE_UL_API_CLOCKING_URL: "changeit"
      secret:
        CLOCKING_SERVICE_UL_API_BEARER_TOKEN: "changeit"

multi-microservice-contact-us:
  appService:
    name: contact-us
    repositoryName: multi-contact-us
    path: /contact-us
    containerPort: 3016
    env:
      normal:
        CONTACT_US_SERVICE_PORT: "3016"
        CONTACT_US_SERVICE_HOST: "0.0.0.0"
        CONTACT_US_SERVICE_SMTP: "changeit"
        CONTACT_US_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        CONTACT_US_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-contacts:
  appService:
    name: contacts
    repositoryName: multi-contacts
    path: /contacts
    containerPort: 3009
    env:
      normal:
        CONTACT_SERVICE_HOST: "0.0.0.0"
        CONTACT_SERVICE_PORT: "3009"
        CONTACTS_SERVICE_UL_API_URL_USER_PROFILE: "changeit"
      secret:
        CONTACTS_SERVICE_UL_API_BEARER_TOKEN: "changeit"

multi-microservice-features:
  appService:
    name: features
    repositoryName: multi-features
    path: /features
    containerPort: 3003
    env:
      normal:
        FEATURES_SERVICE_HOST: "0.0.0.0"
        FEATURES_SERVICE_PORT: "3003"
        FEATURES_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        FEATURES_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-important-news:
  appService:
    name: important-news
    repositoryName: multi-important-news
    path: /important-news
    containerPort: 3011
    env:
      normal:
        IMPORTANT_NEWS_SERVICE_HOST: "0.0.0.0"
        IMPORTANT_NEWS_SERVICE_PORT: "3011"
        IMPORTANT_NEWS_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        IMPORTANT_NEWS_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-mail-calendar:
  appService:
    name: mail-calendar
    repositoryName: multi-mail-calendar
    path: /mail-calendar
    containerPort: 3019
    env:
      normal:
        MAIL_CALENDAR_SERVICE_HOST: 0.0.0.0
        MAIL_CALENDAR_SERVICE_PORT: 3019
        MAIL_CALENDAR_SERVICE_UL_API_URL: "changeit"
      secret:
        MAIL_CALENDAR_SERVICE_UL_BEARER_TOKEN: "changeit"

multi-microservice-map:
  appService:
    name: map
    repositoryName: multi-map
    path: /map
    containerPort: 3005
    env:
      normal:
        MAP_SERVICE_HOST: "0.0.0.0"
        MAP_SERVICE_PORT: "3005"

multi-microservice-notifications:
  appService:
    name: notifications
    repositoryName: multi-notifications
    path: /notifications
    containerPort: 3010
    env:
      normal:
        NOTIFICATIONS_SERVICE_HOST: "0.0.0.0"
        NOTIFICATIONS_SERVICE_PORT: "3010"
        NOTIFICATIONS_SERVICE_UL_API_NOTIFICATIONS_URL: "changeit"
        NOTIFICATIONS_SERVICE_UL_API_CHANNELS_URL: "changeit"
        NOTIFICATIONS_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        NOTIFICATIONS_SERVICE_UL_API_BEARER_TOKEN: "changeit"
        NOTIFICATIONS_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-restaurants:
  appService:
    name: restaurants
    repositoryName: multi-restaurants
    path: /restaurants
    containerPort: 3017
    env:
      normal:
        RESTAURANTS_SERVICE_HOST: "0.0.0.0"
        RESTAURANTS_SERVICE_PORT: "3017"
        RESTAURANTS_UL_API_URL: "changeit"
      secret:
        RESTAURANTS_UL_API_BEARER_TOKEN: "changeit"

multi-microservice-rss:
  appService:
    name: rss
    repositoryName: multi-rss
    path: /rss
    containerPort: 3006
    env:
      normal:
        RSS_SERVICE_HOST: "0.0.0.0"
        RSS_SERVICE_PORT: "3006"
        RSS_SERVICE_FEED_URL: "changeit"
        RSS_SERVICE_ALLOWED_HTML_TAGS: "b,strong,i,italic,ol,ul,li"

multi-microservice-schedule:
  appService:
    name: schedule
    repositoryName: multi-schedule
    path: /schedule
    containerPort: 3008
    env:
      normal:
        SCHEDULE_SERVICE_HOST: "0.0.0.0"
        SCHEDULE_SERVICE_PORT: "3008"
        SCHEDULE_SERVICE_UL_API_USER_SCHEDULE_URL: "changeit"
      secret:
        SCHEDULE_SERVICE_UL_API_BEARER_TOKEN: "changeit"

multi-microservice-social-network:
  appService:
    name: social-network
    repositoryName: multi-social-network
    path: /social-network
    containerPort: 3013
    env:
      normal:
        SOCIAL_NETWORK_SERVICE_HOST: "0.0.0.0"
        SOCIAL_NETWORK_SERVICE_PORT: "3013"
        SOCIAL_NETWORK_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        SOCIAL_NETWORK_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-static-pages:
  appService:
    name: static-pages
    repositoryName: multi-static-pages
    path: /static-pages
    containerPort: 3015
    env:
      normal:
        STATIC_PAGES_SERVICE_HOST: "0.0.0.0"
        STATIC_PAGES_SERVICE_PORT: "3015"
        STATIC_PAGES_SERVICE_DIRECTUS_API_URL: *directusApiUrl
      secret:
        STATIC_PAGES_SERVICE_DIRECTUS_API_BEARER_TOKEN: *directusApiBearerToken

multi-microservice-statistics:
  appService:
    name: statistics
    repositoryName: multi-statistics
    path: /statistics
    containerPort: 3018
    env:
      normal:
        STATISTICS_SERVICE_HOST: 0.0.0.0
        STATISTICS_SERVICE_PORT: "3018"
        STATISTICS_SERVICE_UL_API_URL: "changeit"
      secret:
        STATISTICS_SERVICE_UL_API_BEARER_TOKEN: "changeit"