# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 8

mongodb:
  ports:
    - "27017"
  persistence:
    mountPath: /bitnami/mongodb
  auth:
    existingSecret: "mongodb-secrets"

directus:
  admin:
    email: test@jnesis.com
    password: test
  mariadb:
    auth:
      rootPassword: secret
  extraEnvVars:
    - name: CACHE_ENABLED
      value: "true"
    - name: SERVER_KEEP_ALIVE_TIMEOUT
      value: 0
    - name: SERVER_HEADERS_TIMEOUT
      value: 0

appService:
  name: main
  repositoryName: multi-main
  containerPort: 3000
  env:
    normal:
      API_GATEWAY_SERVER_HOST: "0.0.0.0"
      API_GATEWAY_SERVER_PORT: "3000"
      API_GATEWAY_CORS_ORIGIN: "http://localhost:8100,http://127.0.0.1:8100,http://localhost,capacitor://localhost"
      FEATURES_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      AUTH_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      MAP_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      RSS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      CARDS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      SCHEDULE_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      CONTACTS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      NOTIFICATIONS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      IMPORTANT_NEWS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      CLOCKING_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      SOCIAL_NETWORK_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      CHATBOT_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      STATIC_PAGES_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      CONTACT_US_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      RESTAURANTS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      STATISTICS_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
      MAIL_CALENDAR_SERVICE_NATS_SERVERS: "nats://multi-nats:4222"
    secret:
      AUTH_SERVICE_JWT_SECRET: "changeit"

service:
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# --- Globals ---

global:
  image:
    tag: sandbox
    pullPolicy: Always
    repositoryUrl: registry-ul.jnesis.com
    nodeBaseCommand: ["node", "main.js"]

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: { }
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: { }

  podSecurityContext: { }
  # fsGroup: 2000

  securityContext: { }
    # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  ingress:
    enabled: false
    className: ""
    annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [ ]
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {
    kubernetes.azure.com/agentpool: "agentpoold2s"
  }

  tolerations: []

  affinity: {}

  commonHealthLivenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10

  commonHealthReadinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
