vars:
  CI_BUILD_NUMBER:
    default: 1

platforms:
  android:
    versionCode: $CI_BUILD_NUMBER
    copy:
      - src: ../src/environments/firebase/android/google-services-prod.json
        dest: app/google-services.json
  ios:
    buildNumber: $CI_BUILD_NUMBER
    copy:
      - src: ../../src/environments/firebase/ios/GoogleService-Info-prod.plist
        dest: App/GoogleService-Info.plist