variables:
  CURRENT_DIR: "dev/user-backend-nest/microservices/clocking/"
  CURRENT_PROJECT: "clocking"
  IMAGE_NAME: "backend/multi-clocking"

include: "${CI_PROJET_DIR}/dev/user-backend-nest/template-ci.yml"
