apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  {{- range .Values.images.services }}
  {{- if and .env .env.secret }}
  {{- range $key, $val := .env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}